
const D=window.BRETT_DATA||{}, tracks=window.BRETT_TRACKS||[];
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
$('#year').textContent=new Date().getFullYear();
document.addEventListener('pointermove',e=>{const g=$('#cursorGlow');g.style.left=e.clientX+'px';g.style.top=e.clientY+'px'});
const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.12});$$('.reveal').forEach(x=>io.observe(x));
const countIO=new IntersectionObserver(es=>es.forEach(e=>{if(!e.isIntersecting)return;const el=e.target,end=+el.dataset.count;let n=0,step=Math.max(1,Math.ceil(end/55));const t=setInterval(()=>{n=Math.min(end,n+step);el.textContent=n+(end===25?'+':'');if(n>=end)clearInterval(t)},22);countIO.unobserve(el)}));$$('[data-count]').forEach(x=>countIO.observe(x));

$('#releaseStrip').innerHTML=(D.releases||[]).map(r=>`<article class="release"><small>${r.type} · ${r.year}</small><strong>${r.title}</strong><a href="${r.url||r.spotify}" target="_blank" rel="noopener">${(r.platform||'LISTEN').toUpperCase()} ↗</a></article>`).join('');

function fmtRange(a,b){const o={month:'short',day:'numeric'};const s=new Date(a+'T00:00:00').toLocaleDateString('en-US',o).toUpperCase();if(!b)return s;const e=new Date(b+'T00:00:00').toLocaleDateString('en-US',o).toUpperCase();return`${s} – ${e}`}
const today=new Date().toISOString().slice(0,10);
const upcoming=(D.upcoming||[]).filter(u=>(u.end_date||u.date)>=today);
if(upcoming.length){$('#upcomingGrid').innerHTML=upcoming.map(u=>`<article class="up-card reveal"><div class="up-date"><span>${fmtRange(u.date,u.end_date)}</span><small>${u.date.slice(0,4)}</small></div><div class="up-body"><h3>${u.name}</h3><p>${[u.venue,u.city].filter(Boolean).join(' · ')}</p><div class="up-artists">${(u.artists||[]).slice(0,5).join(' · ')}${(u.artists||[]).length>5?` <span class="more-chip">+${u.artists.length-5} more</span>`:''}</div></div><a class="btn glass up-link" href="${u.url}" target="_blank" rel="noopener">INFO ↗</a></article>`).join('');$$('#upcomingGrid .reveal').forEach(x=>io.observe(x))}else{$('#upcoming').style.display='none'}

$('#pressList').innerHTML=(D.press||[]).map(p=>`<a class="press-row reveal" href="${p.url}" target="_blank" rel="noopener"><span class="press-year">${p.year}</span><strong>${p.title}</strong><span class="press-type">${p.type}</span><span class="press-arrow">↗</span></a>`).join('');$$('#pressList .reveal').forEach(x=>io.observe(x));

const resi=D.residencies||[];
if(resi.length){const seq=`<span class="resi-item hl">CURRENT RESIDENCIES</span>`+resi.map(r=>`<span class="resi-item">${r.name}</span>`).join('');$('#resiTicker').innerHTML=seq+seq;$('#resiGrid').innerHTML=resi.map(r=>`<div class="resi-card"><strong>${r.name}</strong><span>${r.city}</span></div>`).join('')}else{$('.resi-ticker').style.display='none';$('.resi-title').style.display='none'}
const socials=D.socials||[];
if(socials.length){$('#footSocial').innerHTML=socials.map(s=>`<a href="${s.url}" target="_blank" rel="noopener">${s.label}</a>`).join('');$('#bookSocial').innerHTML=socials.map(s=>`<a class="btn glass social-btn" href="${s.url}" target="_blank" rel="noopener">${s.label}</a>`).join('')}

let artistLimit=48;
function renderArtists(){const q=$('#artistSearch').value.toLowerCase();const all=(D.artists||[]).filter(a=>a.toLowerCase().includes(q));const list=q?all:all.slice(0,artistLimit);$('#artistCount').textContent=`${all.length} artists`;$('#artistCloud').innerHTML=list.map((a,i)=>`<span class="artist-chip" style="animation-delay:${Math.min(i,35)*.018}s">${a}</span>`).join('');$('#showArtists').style.display=!q&&artistLimit<all.length?'block':'none'}
$('#artistSearch').addEventListener('input',renderArtists);$('#showArtists').addEventListener('click',()=>{artistLimit=(D.artists||[]).length;renderArtists()});renderArtists();

let currentAudio=null,currentBtn=null,trackFilter='all';
function renderTracks(){const q=$('#trackSearch').value.toLowerCase();const list=tracks.filter(t=>(trackFilter==='all'||t.type===trackFilter)&&Object.values(t).join(' ').toLowerCase().includes(q));$('#trackList').innerHTML=list.map((t,i)=>`<article class="track"><button class="track-play" data-i="${tracks.indexOf(t)}" ${!t.file?'disabled title="Add audio file to activate"':''}>▶</button><div class="track-meta"><strong>${t.title}</strong><small>${t.genre} · ${t.type}</small></div><span class="bpm">${t.bpm} BPM</span><span class="key">${t.key}</span>${t.file&&t.download?`<a class="download" href="${t.file}" download>DOWNLOAD</a>`:`<span class="download disabled">COMING SOON</span>`}</article>`).join('');$$('.track-play').forEach(b=>b.addEventListener('click',()=>playTrack(+b.dataset.i,b)))}
function playTrack(i,b){const t=tracks[i];if(!t.file)return;if(currentAudio){currentAudio.pause();if(currentBtn)currentBtn.textContent='▶'}if(currentBtn===b){currentBtn=null;currentAudio=null;return}currentAudio=new Audio(t.file);currentBtn=b;b.textContent='Ⅱ';currentAudio.play();currentAudio.onended=()=>{b.textContent='▶';currentAudio=null;currentBtn=null}}
$('#trackSearch').addEventListener('input',renderTracks);$$('.filter-pills button').forEach(b=>b.addEventListener('click',()=>{$$('.filter-pills button').forEach(x=>x.classList.remove('active'));b.classList.add('active');trackFilter=b.dataset.filter;renderTracks()}));renderTracks();
if(!tracks.some(t=>t.file)){$('#vault').style.display='none';const vl=$('.nav nav a[href="#vault"]');if(vl)vl.style.display='none'}

const events=D.events||[];const years=[...new Set(events.map(e=>(e.date||'').slice(0,4)).filter(Boolean))].sort((a,b)=>b-a);$('#yearFilter').innerHTML+=[...years].map(y=>`<option>${y}</option>`).join('');
function renderEvents(){const q=$('#eventSearch').value.toLowerCase(),yr=$('#yearFilter').value;const list=events.filter(e=>{const hay=[e.event_name,e.venue,e.city_state,...(e.artists_played_with||[])].join(' ').toLowerCase();return(!q||hay.includes(q))&&(yr==='all'||(e.date||'').startsWith(yr))}).slice(0,60);$('#eventGrid').innerHTML=list.length?list.map(e=>{const i=events.indexOf(e),arts=e.artists_played_with||[],extra=arts.length-4;return`<article class="event" role="button" tabindex="0" data-i="${i}" aria-label="Open details for ${(e.event_name||'event').replace(/"/g,'&quot;')}"><time>${e.date||'DATE ARCHIVED'}</time><h3>${e.event_name||'Event'}</h3><p>${[e.venue,e.city_state].filter(Boolean).join(' · ')}</p><div class="event-artists">${arts.slice(0,4).join(' · ')}${extra>0?` <span class="more-chip">+${extra} more</span>`:''}</div></article>`}).join(''):'<p>No matching event found.</p>';$$('.event[data-i]').forEach(c=>{c.addEventListener('click',()=>openEvent(+c.dataset.i));c.addEventListener('keydown',ev=>{if(ev.key==='Enter'||ev.key===' '){ev.preventDefault();openEvent(+c.dataset.i)}})})}
function fmtDate(d){if(!d)return'DATE ARCHIVED';const dt=new Date(d+'T00:00:00');return isNaN(dt)?d:dt.toLocaleDateString('en-US',{year:'numeric',month:'long',day:'numeric'})}
function initials(name){return(name||'BO').split(/\s+/).map(w=>w[0]).filter(Boolean).slice(0,3).join('').toUpperCase()}
function openEvent(i){const e=events[i];if(!e)return;$('#modalDate').textContent=fmtDate(e.date);const ty=$('#modalType');ty.textContent=e.event_type||'';ty.style.display=e.event_type?'':'none';$('#modalTitle').textContent=e.event_name||'Event';$('#modalLoc').textContent=[e.venue,e.city_state].filter(Boolean).join(' · ');$('#modalArtists').innerHTML=(e.artists_played_with||[]).map(a=>`<span class="artist-chip">${a}</span>`).join('');$('#modalMedia').innerHTML=e.flyer_image?`<img src="${e.flyer_image}" alt="${(e.event_name||'Event')} flyer">`:`<div class="flyer-placeholder"><img src="assets/brett-ortiz-logo.png" alt=""><span>${initials(e.event_name)}</span></div>`;const s=$('#modalSource');if(e.source_url){s.href=e.source_url;s.style.display=''}else{s.style.display='none'}$('#eventModal').classList.add('open');$('#eventModal').setAttribute('aria-hidden','false');document.body.classList.add('modal-open')}
function closeEventModal(){$('#eventModal').classList.remove('open');$('#eventModal').setAttribute('aria-hidden','true');document.body.classList.remove('modal-open')}
$('#closeEventModal').addEventListener('click',closeEventModal);$('#eventModal').addEventListener('click',e=>{if(e.target.id==='eventModal')closeEventModal()});
$('#eventSearch').addEventListener('input',renderEvents);$('#yearFilter').addEventListener('change',renderEvents);renderEvents();

$$('.flyer').forEach(b=>b.addEventListener('click',()=>{$('#lightboxImage').src=b.dataset.src;$('#lightbox').classList.add('open');$('#lightbox').setAttribute('aria-hidden','false')}));function closeLB(){$('#lightbox').classList.remove('open');$('#lightbox').setAttribute('aria-hidden','true')}$('#closeLightbox').addEventListener('click',closeLB);$('#lightbox').addEventListener('click',e=>{if(e.target.id==='lightbox')closeLB()});document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeLB();closeEventModal()}});
